"""empty message

Revision ID: 0ef631084e32
Revises: 
Create Date: 2020-10-10 19:34:27.774296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef631084e32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_type', sa.String(length=32), nullable=False),
    sa.Column('short_change', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('routes',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('delivery_address', sa.String(length=128), nullable=False),
    sa.Column('shipping_address', sa.String(length=128), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('estimated_time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('applications',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('conclusion_date', sa.Date(), nullable=False),
    sa.Column('delivery_route', sa.Integer(), nullable=True),
    sa.Column('payment', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_route'], ['routes.route_id'], ),
    sa.ForeignKeyConstraint(['payment'], ['payments.payment_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('cargos',
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.Column('nomenclature', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('cargo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cargos')
    op.drop_table('applications')
    op.drop_table('routes')
    op.drop_table('payments')
    # ### end Alembic commands ###
