"""empty message

Revision ID: 1242dab2f70b
Revises: e05bb8ab4f54
Create Date: 2020-10-14 20:47:53.255378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1242dab2f70b'
down_revision = 'e05bb8ab4f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('passport_id', sa.Integer(), nullable=False),
    sa.Column('passport_series', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('middle_name', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('contacts',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('middle_name', sa.String(length=32), nullable=True),
    sa.Column('position', sa.String(length=32), nullable=True),
    sa.Column('organization', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('cars',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=1), nullable=False),
    sa.Column('application_detail', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_detail'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('car_id')
    )
    op.create_table('contracts',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('conclusion_date', sa.Date(), nullable=False),
    sa.Column('bank_name', sa.String(length=64), nullable=False),
    sa.Column('BIK', sa.String(length=9), nullable=False),
    sa.Column('INN', sa.String(length=10), nullable=False),
    sa.Column('KPP', sa.String(length=9), nullable=False),
    sa.Column('KS', sa.String(length=20), nullable=False),
    sa.Column('bank_account', sa.String(length=20), nullable=False),
    sa.Column('application_num', sa.Integer(), nullable=True),
    sa.Column('client_detail', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_num'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['client_detail'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('contract_id')
    )
    op.create_table('drivers',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('middle_name', sa.String(length=32), nullable=True),
    sa.Column('categories', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('application_detail', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_detail'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('driver_id')
    )
    op.add_column('applications', sa.Column('consignee_id', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('shipper_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'applications', 'contacts', ['shipper_id'], ['contact_id'])
    op.create_foreign_key(None, 'applications', 'contacts', ['consignee_id'], ['contact_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'shipper_id')
    op.drop_column('applications', 'consignee_id')
    op.drop_table('drivers')
    op.drop_table('contracts')
    op.drop_table('cars')
    op.drop_table('contacts')
    op.drop_table('clients')
    # ### end Alembic commands ###
