"""empty message

Revision ID: 5414654e1d4f
Revises: bf139fd73627
Create Date: 2020-10-10 23:25:42.933653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5414654e1d4f'
down_revision = 'bf139fd73627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('smth', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'smth')
    # ### end Alembic commands ###
