"""empty message

Revision ID: 6a339776590a
Revises: 5414654e1d4f
Create Date: 2020-10-10 23:26:27.759287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a339776590a'
down_revision = '5414654e1d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'smth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('smth', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
