"""changed route time type

Revision ID: 7a40ac279fdd
Revises: 0ef631084e32
Create Date: 2020-10-10 23:07:39.441370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a40ac279fdd'
down_revision = '0ef631084e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('estimated_timee', sa.Integer(), nullable=True))
    op.drop_column('routes', 'estimated_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('estimated_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('routes', 'estimated_timee')
    # ### end Alembic commands ###
