"""changed route time type x2

Revision ID: bf139fd73627
Revises: 7a40ac279fdd
Create Date: 2020-10-10 23:09:28.375285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf139fd73627'
down_revision = '7a40ac279fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('estimated_time', sa.Integer(), nullable=True))
    op.drop_column('routes', 'estimated_timee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('estimated_timee', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('routes', 'estimated_time')
    # ### end Alembic commands ###
