"""test migration

Revision ID: e05bb8ab4f54
Revises: e440f022b864
Create Date: 2020-10-11 03:41:28.571047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e05bb8ab4f54'
down_revision = 'e440f022b864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('name', sa.String(length=128), nullable=False))
    op.drop_column('applications', 'namee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('namee', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('applications', 'name')
    # ### end Alembic commands ###
