"""empty message

Revision ID: e440f022b864
Revises: 6a339776590a
Create Date: 2020-10-11 00:11:33.232784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e440f022b864'
down_revision = '6a339776590a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('payment_detail', sa.Integer(), nullable=True))
    op.drop_constraint('applications_payment_fkey', 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'payments', ['payment_detail'], ['payment_id'])
    op.drop_column('applications', 'payment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('payment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key('applications_payment_fkey', 'applications', 'payments', ['payment'], ['payment_id'])
    op.drop_column('applications', 'payment_detail')
    # ### end Alembic commands ###
