from app.models.Client import Client
from app.models.Application import Application
from app.models.Contract import Contract
from app.models.Contact import Contact
from app.models.Driver import Driver
from app.models.Car import Car
from app.models.Requisite import Requisite
from app.models.Route import Route
from app.models.Cargo import Cargo
